import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import CustomNavbar from "../components/CustomNavbar";
import Footer from "../components/Footer";
import UserProvider from "../context/userProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
console.log("THIS")

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>

        <ToastContainer/>
        <CustomNavbar/>
        {children}
        <Footer/>
        </UserProvider>
      </body>
    </html>
  );
}
